name       : qt5-base
version    : 5.12.2
release    : 36
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.2/submodules/qtbase-everywhere-src-5.12.2.tar.xz : 562c095a59c95f393762ec53bc05c0d80fad1758fd5ff7a5231967d1a98d56c1
license    :
    - FDL-1.3
    - GPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Cross platform application and UI framework
description: |
    Cross platform application and UI Framework
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libinput)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libpcre2-32)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(libpulse)
    - pkgconfig(mariadb)
    - pkgconfig(sqlite3)
    - pkgconfig(vulkan)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xext)
    - pkgconfig(xi)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - cups-devel
rundeps    :
    - devel :
        - mesalib-devel
        - vulkan-devel
patterns   :
    - devel :
        - /usr/bin
        - /usr/lib64/qt5/mkspecs
    - docs :
        - /usr/share/doc/qt5
    - demos :
        - /usr/lib64/qt5/examples
replaces   :
    - qt5
    - demos : qt5-demos
    - devel : qt5-devel
    - docs : qt5-docs
environment: |
    unset LD_AS_NEEDED
setup      : |
    %apply_patches
    sed -i -e 's|^\(QMAKE_STRIP.*=\).*$|\1|g' mkspecs/common/linux.conf
    ./configure -prefix /usr \
                -libdir %libdir% \
                -archdatadir %libdir%/qt5 \
                -bindir /usr/bin \
                -datadir /usr/share/qt5 \
                -docdir /usr/share/doc/qt5 \
                -examplesdir %libdir%/qt5/examples \
                -headerdir /usr/include \
                -sysconfdir /etc/xdg \
                -accessibility \
                -dbus-linked \
                -no-pch \
                -no-rpath \
                -no-strip \
                -no-feature-statx \
                -opensource \
                -openssl-linked \
                -reduce-relocations \
                -shared \
                -sm \
                -system-freetype \
                -system-harfbuzz \
                -system-libjpeg \
                -system-libpng \
                -system-pcre \
                -system-proxies \
                -system-sqlite \
                -system-xcb \
                -system-zlib \
                -verbose \
                -xcb \
                -xkb \
                -cups \
                -fontconfig \
                -glib \
                -gui \
                -egl \
                -eglfs \
                -icu \
                -journald \
                -plugin-sql-sqlite \
                -plugin-sql-mysql \
                -widgets \
                -no-warnings-are-errors \
                -no-use-gold-linker \
                -nomake tests \
                -release \
                -confirm-license \
                QMAKE_CFLAGS_RELEASE="${CFLAGS}" \
                QMAKE_CXXFLAGS_RELEASE="${CXXFLAGS}" \
                QMAKE_LFLAGS_RELEASE="${LDFLAGS}"
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
    # Amend build dir issues
    find $installdir/%libdir% -type f -name '*prl' -exec perl -pi -e "s, -L$workdir/\S+,,g" {} \;
    find $installdir/%libdir% -type f -name '*prl' -exec sed -i -e "/^QMAKE_PRL_BUILD_DIR/d" {} \;
    rm $installdir/%libdir%/cmake/Qt5*/Q*Plugin.cmake
