name       : qt5-base
version    : 5.9.1
release    : 9
source     :
    - http://download.qt.io/official_releases/qt/5.9/5.9.1/submodules/qtbase-opensource-src-5.9.1.tar.xz : bc9a21e9f6fff9629019fdf9f989f064751d5073c3a28dc596def92f4d4275c6
license    :
    - FDL-1.3
    - GPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Cross platform application and UI framework
description: |
    Cross platform application and UI Framework
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libinput)
    - pkgconfig(libpcre2-32)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(libpulse)
    - pkgconfig(mariadb)
    - pkgconfig(sqlite3)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xext)
    - pkgconfig(xi)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - cups-devel
    - libjpeg-turbo-devel
    - zlib-devel
patterns   :
    - devel :
        - /usr/bin
        - /usr/lib64/qt5/mkspecs
    - docs :
        - /usr/share/doc/qt5
    - demos :
        - /usr/lib64/qt5/examples
replaces   :
    - qt5
    - demos : qt5-demos
    - devel : qt5-devel
    - docs : qt5-docs
setup      : |
    %apply_patches
    sed -i -e 's|^\(QMAKE_STRIP.*=\).*$|\1|g' mkspecs/common/linux.conf
    unset LD_AS_NEEDED
    ./configure -prefix /usr \
                -libdir %libdir% \
                -archdatadir %libdir%/qt5 \
                -bindir /usr/bin \
                -datadir /usr/share/qt5 \
                -docdir /usr/share/doc/qt5 \
                -examplesdir %libdir%/qt5/examples \
                -headerdir /usr/include \
                -sysconfdir /etc/xdg \
                -accessibility \
                -dbus-linked \
                -no-pch \
                -no-rpath \
                -no-strip \
                -opensource \
                -openssl-linked \
                -reduce-relocations \
                -shared \
                -sm \
                -system-freetype \
                -system-harfbuzz \
                -system-libjpeg \
                -system-libpng \
                -system-pcre \
                -system-proxies \
                -system-sqlite \
                -system-xcb \
                -system-xkbcommon \
                -system-zlib \
                -verbose \
                -xcb \
                -xkb \
                -cups \
                -fontconfig \
                -glib \
                -gui \
                -egl \
                -eglfs \
                -icu \
                -journald \
                -opengl desktop \
                -plugin-sql-sqlite \
                -plugin-sql-mysql \
                -widgets \
                -no-warnings-are-errors \
                -no-use-gold-linker \
                -nomake tests \
                -xkb-config-root /usr/share/X11/xkb \
                -release \
                -confirm-license
build      : |
    unset LD_AS_NEEDED
    %make
install    : |
    unset LD_AS_NEEDED
    %make_install INSTALL_ROOT="$installdir"
    #Amend build dir issues
    find $installdir%libdir% -type f -name '*prl' -exec perl -pi -e "s, -L$workdir/\S+,,g" {} \;
    find $installdir%libdir% -type f -name '*prl' -exec sed -i -e "/^QMAKE_PRL_BUILD_DIR/d" {} \;
    rm $installdir%libdir%/cmake/Qt5*/Q*Plugin.cmake
